#误差参数 [宽,高](单位：mm)
error_range:
  [ 2,3 ]


#纸张尺寸，[宽,高](单位：mm)
papersize:
  A4: [ 210,297 ]
  A5: [ 149,210 ]
  A6: [ 105,148 ]
  B5_JIS: [ 182,257 ]
  Letter: [ 215.9,279.4 ]
  Legal: [ 215.9,355.6 ]



#case标题项
options:
  scanning_mode: [ '纸张来源','单双面' ]              #扫描模式
  expected_bit_depth: 'Expected_bit_depth'    #预期位深
  expected_color_mode: '色彩模式'  #色彩模式
  paper_size: '纸张大小'                    #纸张尺寸
  expected_dpi: '分辨率'                #预期DPI
  scaling_ratio: 'Scaling_ratio'              #缩放比例
  preservation_method: '保存格式'  #保存方式


  #资源路径
path:
  prefix: 'resources/'
  case_path: 'case.xlsx'
  reference_path: 'reference_image'

